urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^blinddata/', include('blinddata.foo.urls')),

    #filter by country
    #(r'^(?P<alpha2_code>\w{2})/$', 'blinddata.views.index'),
    #(r'^(?P<alpha2_code>\w{2})/(?P<safe_topic>\w+)/$', 'blinddata.views.index'),
    #(r'^(?P<alpha2_code>\w{2})/(?P<safe_topic>\w+)/(?P<safe_subtopic>\w+)/$', 'blinddata.views.index'),
    #(r'^(?P<alpha2_code>\w{2})/(?P<safe_topic>\w+)/(?P<safe_subtopic>\w+)/(?P<safe_series>\w+)/$', 'blinddata.views.index'),

    (r'^admin/', include(admin.site.urls)),

    # no filter
    (r'^$', 'blinddata.views.index'),
    (r'^(?P<topic_slug>[\w-]+)/$', 'blinddata.views.topic_detail'),
    (r'^(?P<topic_slug>[\w-]+)/(?P<subtopic_slug>[\w-]+)/$', 'blinddata.views.subtopic_detail'),
    (r'^(?P<topic_slug>[\w-]+)/(?P<subtopic_slug>[\w-]+)/(?P<series_code_slug>[\w-]+)/$', 'blinddata.views.series_detail'),

	#testing and development
    #(r'^crawl/$', 'blinddata.views.crawl'),
    #(r'^map/$', 'blinddata.views.map'),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': '/home/thebenedict/src/blinddata/static_files'}),

)

forms.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from django import forms

COUNTRY_CHOICES = (
    ('',    'None'),
    ('East Asia & Pacific', (
            ('ASM', 'American Samoa'),
            ('AUS', 'Australia'),
            ('BRN', 'Brunei Darussalam'),
            ('KHM', 'Cambodia'),
            ('CHN', 'China'),
            ('FJI', 'Fiji'),
            ('PYF', 'French Polynesia'),
            ('GUM', 'Guam'),
            ('HKG', 'Hong Kong SAR, China'),
            ('IDN', 'Indonesia'),
            ('JPN', 'Japan'),
            ('KIR', 'Kiribati'),
            ('PRK', 'Korea, Dem. Rep.'),
            ('KOR', 'Korea, Rep.'),
            ('LAO', 'Lao PDR'),
            ('MAC', 'Macao SAR, China'),
            ('MYS', 'Malaysia'),
            ('MHL', 'Marshall Islands'),
            ('FSM', 'Micronesia, Fed. Sts.'),
            ('MNG', 'Mongolia'),
            ('MMR', 'Myanmar'),
            ('NCL', 'New Caledonia'),
            ('NZL', 'New Zealand'),
            ('MNP', 'Northern Mariana Islands'),
            ('PLW', 'Palau'),
            ('PNG', 'Papua New Guinea'),
            ('PHL', 'Philippines'),
            ('WSM', 'Samoa'),
            ('SGP', 'Singapore'),
            ('SLB', 'Solomon Islands'),
            ('THA', 'Thailand'),
            ('TMP', 'Timor-Leste'),
            ('TON', 'Tonga'),
            ('TUV', 'Tuvalu'),
            ('VUT', 'Vanuatu'),
            ('VNM', 'Vietnam'),
        )
    ),
    ('Europe & Central Asia', (
            ('ALB', 'Albania'),
            ('ADO', 'Andorra'),
            ('ARM', 'Armenia'),
            ('AUT', 'Austria'),
            ('AZE', 'Azerbaijan'),
            ('BLR', 'Belarus'),
            ('BEL', 'Belgium'),
            ('BIH', 'Bosnia and Herzegovina'),
            ('BGR', 'Bulgaria'),
            ('CHI', 'Channel Islands'),
            ('HRV', 'Croatia'),
            ('CYP', 'Cyprus'),
            ('CZE', 'Czech Republic'),
            ('DNK', 'Denmark'),
            ('EST', 'Estonia'),
            ('FRO', 'Faeroe Islands'),
            ('FIN', 'Finland'),
            ('FRA', 'France'),
            ('GEO', 'Georgia'),
            ('DEU', 'Germany'),
            ('GIB', 'Gibraltar'),
            ('GRC', 'Greece'),
            ('GRL', 'Greenland'),
            ('HUN', 'Hungary'),
            ('ISL', 'Iceland'),
            ('IRL', 'Ireland'),
            ('IMY', 'Isle of Man'),
            ('ITA', 'Italy'),
            ('KAZ', 'Kazakhstan'),
            ('KSV', 'Kosovo'),
            ('KGZ', 'Kyrgyz Republic'),
            ('LVA', 'Latvia'),
            ('LIE', 'Liechtenstein'),
            ('LTU', 'Lithuania'),
            ('LUX', 'Luxembourg'),
            ('MKD', 'Macedonia, FYR'),
            ('MDA', 'Moldova'),
            ('MCO', 'Monaco'),
            ('MNE', 'Montenegro'),
            ('NLD', 'Netherlands'),
            ('NOR', 'Norway'),
            ('POL', 'Poland'),
            ('PRT', 'Portugal'),
            ('ROM', 'Romania'),
            ('RUS', 'Russian Federation'),
            ('SMR', 'San Marino'),
            ('SRB', 'Serbia'),
            ('SVK', 'Slovak Republic'),
            ('SVN', 'Slovenia'),
            ('ESP', 'Spain'),
            ('SWE', 'Sweden'),
            ('CHE', 'Switzerland'),
            ('TJK', 'Tajikistan'),
            ('TUR', 'Turkey'),
            ('TKM', 'Turkmenistan'),
            ('UKR', 'Ukraine'),
            ('GBR', 'United Kingdom'),
            ('UZB', 'Uzbekistan'),
        )
    ),
    ('Latin America & Caribbean', (
            ('ATG', 'Antigua and Barbuda'),
            ('ARG', 'Argentina'),
            ('ABW', 'Aruba'),
            ('BHS', 'Bahamas, The'),
            ('BRB', 'Barbados'),
            ('BLZ', 'Belize'),
            ('BOL', 'Bolivia'),
            ('BRA', 'Brazil'),
            ('CYM', 'Cayman Islands'),
            ('CHL', 'Chile'),
            ('COL', 'Colombia'),
            ('CRI', 'Costa Rica'),
            ('CUB', 'Cuba'),
            ('DMA', 'Dominica'),
            ('DOM', 'Dominican Republic'),
            ('ECU', 'Ecuador'),
            ('SLV', 'El Salvador'),
            ('GRD', 'Grenada'),
            ('GTM', 'Guatemala'),
            ('GUY', 'Guyana'),
            ('HTI', 'Haiti'),
            ('HND', 'Honduras'),
            ('JAM', 'Jamaica'),
            ('MEX', 'Mexico'),
            ('ANT', 'Netherlands Antilles'),
            ('NIC', 'Nicaragua'),
            ('PAN', 'Panama'),
            ('PRY', 'Paraguay'),
            ('PER', 'Peru'),
            ('PRI', 'Puerto Rico'),
            ('KNA', 'St. Kitts and Nevis'),
            ('LCA', 'St. Lucia'),
            ('VCT', 'St. Vincent and the Grenadines'),
            ('SUR', 'Suriname'),
            ('TTO', 'Trinidad and Tobago'),
            ('TCA', 'Turks and Caicos Islands'),
            ('URY', 'Uruguay'),
            ('VEN', 'Venezuela, RB'),
            ('VIR', 'Virgin Islands (U.S.)'),
        )
    ),
    ('Middle East & North Africa', (
            ('DZA', 'Algeria'),
            ('BHR', 'Bahrain'),
            ('DJI', 'Djibouti'),
            ('EGY', 'Egypt, Arab Rep.'),
            ('IRN', 'Iran, Islamic Rep.'),
            ('IRQ', 'Iraq'),
            ('ISR', 'Israel'),
            ('JOR', 'Jordan'),
            ('KWT', 'Kuwait'),
            ('LBN', 'Lebanon'),
            ('LBY', 'Libya'),
            ('MLT', 'Malta'),
            ('MAR', 'Morocco'),
            ('OMN', 'Oman'),
            ('QAT', 'Qatar'),
            ('SAU', 'Saudi Arabia'),
            ('SYR', 'Syrian Arab Republic'),
            ('TUN', 'Tunisia'),
            ('ARE', 'United Arab Emirates'),
            ('WBG', 'West Bank and Gaza'),
            ('YEM', 'Yemen, Rep.'),
        )
    ),
    ('North America', (
            ('BMU', 'Bermuda'),
            ('CAN', 'Canada'),
            ('USA', 'United States'),
        )
    ),
    ('South Asia', (
            ('AFG', 'Afghanistan'),
            ('BGD', 'Bangladesh'),
            ('BTN', 'Bhutan'),
            ('IND', 'India'),
            ('MDV', 'Maldives'),
            ('NPL', 'Nepal'),
            ('PAK', 'Pakistan'),
            ('LKA', 'Sri Lanka'),
        )
    ),
    ('Sub-Saharan Africa', (
            ('AGO', 'Angola'),
            ('BEN', 'Benin'),
            ('BWA', 'Botswana'),
            ('BFA', 'Burkina Faso'),
            ('BDI', 'Burundi'),
            ('CMR', 'Cameroon'),
            ('CPV', 'Cape Verde'),
            ('CAF', 'Central African Republic'),
            ('TCD', 'Chad'),
            ('COM', 'Comoros'),
            ('ZAR', 'Congo, Dem. Rep.'),
            ('COG', 'Congo, Rep.'),
            ('CIV', 'Côte d\'Ivoire'),
            ('GNQ', 'Equatorial Guinea'),
            ('ERI', 'Eritrea'),
            ('ETH', 'Ethiopia'),
            ('GAB', 'Gabon'),
            ('GMB', 'Gambia, The'),
            ('GHA', 'Ghana'),
            ('GIN', 'Guinea'),
            ('GNB', 'Guinea-Bissau'),
            ('KEN', 'Kenya'),
            ('LSO', 'Lesotho'),
            ('LBR', 'Liberia'),
            ('MDG', 'Madagascar'),
            ('MWI', 'Malawi'),
            ('MLI', 'Mali'),
            ('MRT', 'Mauritania'),
            ('MUS', 'Mauritius'),
            ('MYT', 'Mayotte'),
            ('MOZ', 'Mozambique'),
            ('NAM', 'Namibia'),
            ('NER', 'Niger'),
            ('NGA', 'Nigeria'),
            ('RWA', 'Rwanda'),
            ('STP', 'São Tomé and Principe'),
            ('SEN', 'Senegal'),
            ('SYC', 'Seychelles'),
            ('SLE', 'Sierra Leone'),
            ('SOM', 'Somalia'),
            ('ZAF', 'South Africa'),
            ('SDN', 'Sudan'),
            ('SWZ', 'Swaziland'),
            ('TZA', 'Tanzania'),
            ('TGO', 'Togo'),
            ('UGA', 'Uganda'),
            ('ZMB', 'Zambia'),
            ('ZWE', 'Zimbabwe'),
        )
    ),
)

class SessionSettingsForm(forms.Form):
    start_year = forms.IntegerField(label='Start year', \
                                    required=False, \
                                    min_value=1960, \
                                    max_value=2008, \
                                    widget=forms.TextInput(attrs={'class':'year_entry'}))
    end_year = forms.IntegerField(label='End year', \
                                  required=False, \
                                  min_value=1961, \
                                  max_value=2009, \
                                  widget=forms.TextInput(attrs={'class':'year_entry'}))
    country_one = forms.CharField(label='Filter by country', \
                                  required=False, \
                                  max_length=50, \
                                  widget=forms.Select(choices=COUNTRY_CHOICES))
    country_two = forms.CharField(label='Compare wth', \
                                  required=False, \
                                  max_length=50, \
                                  widget=forms.Select(choices=COUNTRY_CHOICES,attrs={'class':'country_two'}))
                 

templates/blinddata_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.7/themes/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/tables.css" >
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

  <!--Jquery range slider-->
	<script>
	$(function() {
		$( "#slider-range" ).slider({
			range: true,
			min: 1960,
			max: 2009,
                        {% if table %}
			    values: [ {{ table.start_year }}, {{ table.end_year }} ],
                        {% else %}
                            values: [ {{ series_row.start_year }}, {{  series_row.end_year }} ],
                        {% endif %}
			slide: function( event, ui ) {
				$( "#id_start_year" ).val( ui.values[ 0 ] );
                                $( "#id_end_year" ).val( ui.values[ 1 ] );
			}
		});
		$( "#id_start_year" ).val( $( "#slider-range" ).slider( "values", 0 ));
                $( "#id_end_year" ).val( $( "#slider-range" ).slider( "values", 1 ));
	});
	</script>
  <!--End Jquery range slider -->

<!--Jquery div show/hide slider-->
	<script>
	$(function() {
		// run the currently selected effect
		function runEffect() {
			var selectedEffect = "slide";
			var options = {mode: 'show'};
			$( "#slider" ).toggle( selectedEffect, options, 300 );
		};
		
		// set effect from select menu value
		$( "#form_button" ).click(function() {
			runEffect();
			return false;
		});
	});
	</script>
<!--End Jquery div show/hide slider-->

  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Blind Data</title>
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['geomap']});

    function drawVisualization() {
      var data = new google.visualization.DataTable();
      data.addRows({{ map_data|length }});
      data.addColumn('string', 'Country');
      data.addColumn('number', 'Datapoints');
      data.addColumn('string', 'Name');
      {% for name, code, number in map_data %}
      data.setValue({{ forloop.counter0 }}, 0, '{{ code }}');
      data.setValue({{ forloop.counter0 }}, 1, {{ number }});
      data.setValue({{ forloop.counter0 }}, 2, '{{ name }}');
      {% endfor %}
      
      var options = {};
      options['width'] = '750px';
      options['dataMode'] = 'regions';
      {% if map_data|length_is:"1" %}
          options['region'] = '{{ map_data.0.1 }}'
          options['dataMode'] = 'markers';
          options['showLegend'] = false;
      {% endif %}
      var geomap = new google.visualization.GeoMap(
          document.getElementById('visualization'));
          
/*      google.visualization.events.addListner(geomap, 'select', function(){
        alert('click');
      });*/
          
/*      google.visualization.events.addListner(geomap, 'regionClick', function(e) {
          alert('click! ' + e['region']);
          //var rowindex = data.getFilteredRows([{column: 0, value: e['region']}]);
          //var country_code = data.getValue(rowindex[0],0);
      });*/
 
/* UNCOMMENT TO MAKE THE MAP CLICKABLE     
      google.visualization.events.addListener(geomap, 'regionClick', regionClickHandler);
      
      function regionClickHandler(e) {
        var rowindex = data.getFilteredRows([{column: 0, value: e['region']}]);
        var country_code = data.getValue(rowindex[0],0);
*/        
        //the above two lines work, the below two take two clicks on the map to do the same thing
        //I don't understand why
        //var country_data = geomap.getSelection();
        //var country_code = data.getValue(country_data[0].row,0);
/* UNCOMMENT TO MAKE THE MAP CLICKABLE        
        location.href = "http://" + location.host + '/' + country_code + location.pathname;

        geomap.setSelection();
      }
*/      
      geomap.draw(data, options);
    }
    

    google.setOnLoadCallback(drawVisualization);
  </script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3319511-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
    <div id="header">
        {% block header %}
            <h1>BLIND DATA</h1>
            <h2>Data Availablility in the WDI and GDF</h2>
            <hr>
        {% endblock %}
    </div>

    <div id="filters">
        {% block filters %}{% endblock %}
    </div>


<div id="form-wrapper">

<div id="form-toggle">
    <a href="#" id="form_button">Options</a>
</div>

    <div id="slider">
    <div id="slider-range"></div>    
        <form action="/" method="post">
            {{ session_settings_form.as_p }}
            <input type="submit" value ="Apply" />
        </form>
    
    </div>  

</div>

    <div id="content">

        {% block content %}{% endblock %}
        <div id="visualization"></div>
    </div>
   
    <div id ="footer">
        {% block footer %}
            <smalltext>Blind Data was made in 2010 and 2011 by Michael Benedict. Data courtesy of the
             <a href="http://worldbank.org">World Bank Group</a>, provided under these <a href="http://www.worldbank.org/terms-datasets"> terms of use</a>.<br/> For more information see <a href ="http://data.worldbank.org">http://data.worldbank.org</a>, and send questions, comments, and bugs to thebenedict at gmail.
             <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/80x15.png" /></a>
        {% endblock %}
    </div>
</body>
</html>